[package]
name = "advent_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
common.workspace = true
test-case.workspace = true
regex.workspace = true
fancy-regex.workspace = true
grid.workspace = true
